### ISSUE TITLE
Current month is overwritten

### ISSUE THREAD

**Issue by oakleybrunt** [liz-stippell/spotify_data#1]
You have overwritten the `current_month` variable here, it looks like it should be called ``current_year`.

```
current_month = current_datetime.strftime("%B") # Automatically computes current month if you want to do it monthly
current_month = "2024"
```

**Comment by liz-stippell** [comment]
Yes, so I was originally using the code for monthly check-ins, so that is why it is called `current_month` instead of `current_year`. To run it how it was originally used, comment the `current_month = "2024"` line.
