### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Flammepiste999** [liz-stippell/spotify_data#3]
Hi, when I run the program I get this error (the problem is probably mine, I don't know much about Python) 
![Capture d'écran 2024-12-08 163242](https://github.com/user-attachments/assets/b4de0aa4-21c4-46e6-9ac3-36c9c43d4a43)

**Comment by Duued** [comment]
I'm here to confirm it's not just you. I'll try to see if I can debug it and fix it. If I do I'll open a pull request.

**Comment by Duued** [comment]
Can I have link in your WRAP variable?

**Comment by samiam808** [comment]
I had this issue at first too. I fixed it by adding the following headers to my google docs sheet. 
date, song, artist, track_id, spotify_link

**Comment by Duued** [comment]
Hey! I just found your issue. Ensure you are putting the correct headers on your spreadsheet.

Column A must be "date" 
Column B must be "song"
Column C must be "artist"

These are case-sensitive.

I will create a pull request allowing the user to change the name of the columns within the code.

**Comment by Flammepiste999** [comment]
THANK YOU GUYS IT WORKS I LOVE YOU
